{% set name = "openfermionpsi4" %}
{% set version = "0.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/openfermionpsi4-{{ version }}.tar.gz
  sha256: 4211f40cc1257777dd5a6e808fdfff51d7e5854e821272633746428fc2b8f9b0

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - openfermion >=0.5
    - python >={{ python_min }}

test:
  imports:
    - openfermionpsi4
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.openfermion.org/
  summary: A plugin allowing OpenFermion to interface with Psi4.
  license: LGPL-3.0-or-later
  license_file:
    - LICENSE
    - NOTICE
  dev_url: https://github.com/quantumlib/OpenFermion-Psi4

extra:
  recipe-maintainers:
    - BastianZim
